apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  namespace: default
  name: vercel-access-binding
subjects:
- kind: ServiceAccount
  name: vercel-sa
  namespace: default
roleRef:
  kind: Role
  name: vercel-access
  apiGroup: rbac.authorization.k8s.io