apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: default
  name: vercel-access
rules:
  - apiGroups: ["*"]  
    resources: ["*"]  
    verbs: ["get", "list", "watch","create", "get", "list", "delete"] 
