apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-name
  labels:
    app: service-name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-name
  template:
    metadata:
      labels:
        app: service-name
    spec:
      volumes:
        - name: workspace-volume
          emptyDir: {}
      initContainers:
        - name: copy-azure-object-store-resources
          image: mcr.microsoft.com/azure-cli
          command: ["/bin/sh", "-c"]
          args:
            - |
              az storage blob download-batch --source coding-platform --pattern "code/userId/projectId/*" --destination ./workspace && echo "Resources copied from Azure Blob"
          env:
            - name: AZURE_STORAGE_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: azure-storage-secret
                  key: AZURE_STORAGE_CONNECTION_STRING
          volumeMounts:
            - name: workspace-volume
              mountPath: /workspace
      containers:
      - name: runner
        image: ashwin06/runner:latest
        ports:
        - containerPort: 3001
        - containerPort: 3000
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 250m
            memory: 512Mi
        env:
        - name: AZURE_STORAGE_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: azure-storage-secret
              key: AZURE_STORAGE_CONNECTION_STRING
        - name: AZURE_CONTAINER_NAME
          value: "coding-platform"
        - name: NODE_ENV
          value: "production"
        volumeMounts:
        - name: workspace-volume
          mountPath: /workspace
          
---
apiVersion: v1
kind: Service
metadata:
  name: service-name
spec:
  selector:
    app: service-name
  ports:
    - protocol: TCP
      name: web-socket-server
      port: 3001
      targetPort: 3001
    - protocol: TCP
      name: user
      port: 3000
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: service-name
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/websocket-services: "service-name:3001"  # Specify port
    nginx.ingress.kubernetes.io/upstream-hash-by: "$remote_addr"         # Add for sticky sessions
    nginx.ingress.kubernetes.io/proxy-buffering: "off"                   # Add this
    nginx.ingress.kubernetes.io/configuration-snippet: |                 # Add this
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
  # Remove these DigitalOcean annotations from Ingress - they belong in Service
  # service.beta.kubernetes.io/do-loadbalancer-name: "load-balancer"
  # service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: service-name.code.ashwinkhowala.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service-name
            port:
              number: 3001
  - host: service-name.out.ashwinkhowala.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service-name
            port:
              number: 3000